### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by xan2622** [Shriinivas/blenderbezierutils#1]
Hi Shriinivas.

As far as I know, you can't release your **Flexi Draw Bezier Tool** under the MIT license. 
It has to be GPL (btw, all blender addons have to be released under the GPL license, not only yours).

https://www.blender.org/about/license/

**Comment by xan2622** [comment]
I invite you to read this comment : 
https://github.com/CGCookie/blender-addon-updater/issues/25#issuecomment-348546237

**Comment by Shriinivas** [comment]
Thank you. I have changed the license type to GPL.
