### ISSUE TITLE
New error while editing a curve

### ISSUE THREAD

**Issue by xan2622** [Shriinivas/blenderbezierutils#12]
New error that I noticed while editing a curve:

Original report: https://blenderartists.org/t/flexi-bezier-tool/1168179/382

Addon version: **0.9.85**
Blender version: **blender-2.83-11df5443e5d0-windows64**

> 
> Traceback (most recent call last):
>   File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbezierutils.py", line 4439, in modal
>     return self.subModal(context, event, evtCons)
>   File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbezierutils.py", line 7259, in subModal
>     changed = ei.insertNode(handleType)
>   File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbezierutils.py", line 6249, in insertNode
>     invMw = obj.matrix_world.inverted()
> NameError: name 'obj' is not defined
> 
> location: <unknown location> : -1:

1. create a curve
2. edit it with Flexi Edit Bezier
3. press CTRL + double click on it

**Comment by Shriinivas** [comment]
This is fixed in the latest version. Kindly check and confirm.

**Comment by xan2622** [comment]
I confirm it is fixed.
Thank you.
