### ISSUE TITLE
Flexi edit bezier not working correctly

### ISSUE THREAD

**Issue by BW2001** [Shriinivas/blenderbezierutils#13]
First noticed when Set Handle Type/Select/Deselect pie menus not working. Used latest version with Blender 2.81a  clean setup (no user addons). The system console window showed output below:

![flexi edit click](https://user-images.githubusercontent.com/61478602/75290521-67abe780-5818-11ea-9507-73fcebaa28a9.png)

In fact error output can occur on first click of flexi edit bezier button.
Error is marked as line 5709 updateaftergeomchange  self.updatesnaplocs()

**Comment by Shriinivas** [comment]
After re-installing the add-on you need restart Blender. Did you do that?
Are you still facing this problem, i.e. does Flexi Edit not work at all for you?

**Comment by BW2001** [comment]
I just fired up Blender 2.81a   Flexi version is 0.9.91
Can create a curve with Flexi Draw – say 4 vertices closed with shift return.
Clicking on Flexi Edit gives the error I reported. A (Alt A )and S pies popup successfully but don’t perform action ie select/deselect points and set type aligned. Interesting, if I perform a standard blender operation ie Grab the error shows up.

I can manually select/move segments/points successfully and use K and W. With W – subdivide, it would be nice to see the number of divisions in the interface and even better if you can type the number you want. H works. Delete works fine.

By the way, this a super addon. Do I ask for feature requests through github or blender artists?

**Comment by Shriinivas** [comment]
It will be dfficult for me to work on the case unless I understand and am able to reproduce the issue. So far I have not faced a similar problem and it's not reported by any other user as yet.
But from your description of the defect, there seem to be more than once instance of the add-on running. So maybe you can try doing the following: 
- Uninstall the add-on
- Close Blender 
- Go to the config directory where add-ons are installed (you will find this in the add-on description)
- Delete blenderbezierutils.py
- Download and install the latest version from this link: https://raw.githubusercontent.com/Shriinivas/blenderbezierutils/master/blenderbezierutils.py

The A (Select) and S (Set Handle Type) menus (and a most other) work only if there are any selections or the mouse pointer hovers over a segment or point. For instance, to select all Bezier points, select a segment of (or hover the mouse over) any point / segment from the curve (or rather spline) of which you want to select the points and then invoke the menu.

**Comment by BW2001** [comment]
I uninstalled “preferences – removed” blenderbezierutils,
closed blender,
deleted both config and scripts folders in <user>/Appdata/Roaming/Blender Foundation/Blender/2.81  which forces Blender to recreate default settings
started blender
Downloaded new version from your github
installed blenderbezierutils

still got error – see attached
the interesting line is “addon_utils.disable: blenderbezierutils no disabled”. Does Blender store info somewhere else? Had a look in program files but nothing.

Might try with Blender 2.82 – will keep trying.

**Comment by Shriinivas** [comment]
I was able to reproduce the issue and have fixed it in the latest version.
Thank you for reporting it. Kindly confirm the fix.

**Comment by BW2001** [comment]
No more error messages in console window. S and A pie menus don’t work in 2.81 and 2.82   on windows 7 system.
However, on a windows 10 system everything works fine. Must convert work machine to windows 10

**Comment by Shriinivas** [comment]
Closing the issue as it's fixed.
PS: You may also want to give Linux a try. It's very robust.
