### ISSUE TITLE
Changing handle type via S pie

### ISSUE THREAD

**Issue by BW2001** [Shriinivas/blenderbezierutils#15]
Playing around with spline options. Had an error with setting handle type via S pie menu

![set handle type error](https://user-images.githubusercontent.com/61478602/77742141-e6f62c00-700d-11ea-8fb7-045c0fc837dd.png)

**Comment by Shriinivas** [comment]
You seem to be using an older version of the add-on. Can you try with the latest one?

**Comment by BW2001** [comment]
OK using 0.9.91 from 19/3/2020
Will try with 0.9.93 but I doubt I will be able to reproduce. I didn’t save the blend file.

**Comment by Shriinivas** [comment]
Please reopen if you encounter this issue again.
