### ISSUE TITLE
Flexi Grease pencil strokes don't get user radius

### ISSUE THREAD

**Issue by Pullusb** [Shriinivas/blenderbezierutils#16]
Not an issue, but more like a "missing feature" that is not too hard to implement I think.

I already left this suggestion as comment on [your youtube video](https://www.youtube.com/watch?v=4XrjpWwLU4M&list=PLxsh4i5F_h9G6QFoPzKvBRMayz8533fSW&index=5&t=0s) but I thought maybe opening this is better for you to track and I can develop the idea.

`line_width` prop take the radius of the user when drawing normal GP.

`C.object.data.layers.active.active_frame.strokes[-1].line_width`

Here it is set at default value `0`.
I think it would be best to use current brush radius so the user can control the thickness of the generated stroke as if he was drawing normally.

it's a per brush `size` parameter.
`C.scene.tool_settings.gpencil_paint.brush.size` to reach the property.

I suppose it would be nice to display the built-in radius property in the toolbar to have a visual on the current value even in Flexi mode (and for user who dont use the `F` shortcut to change it)

Doing the same things for the strength can complete the arsenal (but stored at `points` level this time)
`C.scene.tool_settings.gpencil_paint.brush.strength`

Other than that everything is amazing ! 🚀 
Thank you for coding and sharing this powerfull tool.

Samuel.

**Comment by Shriinivas** [comment]
Thank you very much for the tip. I have implemented this in the latest version.

**Comment by Pullusb** [comment]
Thanks ! Works like a charm
