### ISSUE TITLE
Locks on Flexi Grease

### ISSUE THREAD

**Issue by J-2-Me** [Shriinivas/blenderbezierutils#17]
Not sure what's causing this, it seems to happen sporadically and I can't effectively reproduce it the same way every time.
![issue_01](https://user-images.githubusercontent.com/6830267/80383254-b2b0ac80-88e6-11ea-9512-13bc9e1bc5d1.png)
![issue_02](https://user-images.githubusercontent.com/6830267/80383256-b3e1d980-88e6-11ea-8e5e-5cf55d7b0252.png)

**Comment by Shriinivas** [comment]
I have added code to handle the condition. Please re-open the defect if you come across it again.
