### ISSUE TITLE
Error while dragging a segment

### ISSUE THREAD

**Issue by discodzen** [Shriinivas/blenderbezierutils#19]
Blender 2.83 Win8.1

**Comment by Shriinivas** [comment]
Can you share your blend file. You can attach it in your message here or send it directly to khemadeva@gmail.com.

**Comment by discodzen** [comment]
https://mega.nz/file/0YhjVDLY#HB_A798iMFeXxQqYuWBu7R5_HCCHwFTlJNhFPpFb8N4

**Comment by Shriinivas** [comment]
It's a 311 MB file. Can you give me a file with only the objects that are causing the problem.

**Comment by discodzen** [comment]
[untitled.zip](https://github.com/Shriinivas/blenderbezierutils/files/4892369/untitled.zip)

**Comment by Shriinivas** [comment]
Thanks. The issue is fixed in the latest version. Please check and confirm.

**Comment by discodzen** [comment]
I cant install addon.
![изображение](https://user-images.githubusercontent.com/67185296/87123067-bbcadc00-c28e-11ea-9da7-e3ff7800169d.png)

**Comment by Shriinivas** [comment]
Sorry about that. Please try with the latest version.

**Comment by discodzen** [comment]
Works fine. Thanks!
And
If it is possible. Addon requires improved performance.
https://www.youtube.com/watch?v=zrFcHUBiYRk

**Comment by Shriinivas** [comment]
Yes, performance can sometimes be a problem, especially if there are lot of curve segments.
You can try decreasing the 'Display Curve Resolution' from the add-on preferences to see if that helps.
