### ISSUE TITLE
Is there a way to change stroke styles when drawing using Flexi-Bezier curves?

### ISSUE THREAD

**Issue by mcolinp** [Shriinivas/blenderbezierutils#2]
I love this add-on; though I'm struggling to find a way to change the stroke/brush style while using the Flexi-Bezier Curves in Draw Mode. What I want is to be able to have the thick to thin fall-off at the ends of the lines; and perhaps lower strength as well as the thickness fades to thin. (Pretty Much what the standard Soft Pencil brush would do . . .) 

I also would be interested to know if there is a way to edit these attributes after the fact; aside from 'Sculpt Mode'. I don't really like how the results in Sculpt Mode tend to be a little unnatural & forced most of the time. (If you are trying to make really clean and smooth line work . . .)

**Comment by Shriinivas** [comment]
Thank you for your inputs. I believe, this is about Flexi Grease Bezier. Currently, the tool does not support brush selection, but I understand this is an important feature, so it may be added in future.

**Comment by mcolinp** [comment]
While I wrote that, I actually was using the Object Mode Flexi Draw Bézier curves. Though I would like to have the ability to apply predefined stylized strokes to them as well. Though being able to do it in either Object mode created curves, or draw mode grease pencil curves; would certainly be an improvement. 

Thanks for your quick response. It’s helpful to understand the nuances of how I will develop my workflow in the meantime. 

If you have never looked at Autodesk’s Sketchbook Designer; you should. It was a great program which they unceremoniously retired much to my dismay. I still have it, if you are interested in seeing it’s features in action; I would happily do a screen share through Skype, etc. 
there are many videos on YouTube that show it in action as well. I think I saw someone showing a video of a car sideview concept in the comments on one of your posts in a Blender related forum. 
It is the same software I’m talking about.

**Comment by Shriinivas** [comment]
Yes, I saw the video posted on BlenderArtists forum and it showed some cool features. 
The Flexi tools are still evolving, and I hope over a period of next few weeks, you may see a pretty decent toolkit.
