### ISSUE TITLE
Feature request: Offset curve (inset, outset)

### ISSUE THREAD

**Issue by raindropsfromsky** [Shriinivas/blenderbezierutils#21]
Inspiration for this feature is from InkScape, where we can select a curve, and create another curve that is parallel to the existing curve, either inside ("inset") or outside ("outset"). The amount of offset can be selected with a slider, or spinner control ("dynamic offset").

While the offsetting in InkScape is 2D, it would have to be 3D in Blender. However, conceptually this should be possible by constraining different axes.

**Comment by Shriinivas** [comment]
Thank you for your inputs. This feature is already under consideration. Please use the BlenderArtists thread: https://blenderartists.org/t/flexi-bezier-tool/1168179 for feature requests. This allows brainstorming the ideas with the existing users.
It's better to reserve this Github issues page for Issues (i.e. defects) only.
