### ISSUE TITLE
Feature request: Add midpoints of segments as snap-points

### ISSUE THREAD

**Issue by raindropsfromsky** [Shriinivas/blenderbezierutils#22]
There is a built-in addon called **snap utlities line**, which shows snap points as we move the mouse pointer.

- If we get close to the mid-point of the edge, it snaps to the mid-point and changes the color of the point.

Can it be done with Bezier Utilities also?

Also consider if the midpoints of a face can be highlighted when the mouse pointer is within a threshold distance.

**Comment by Shriinivas** [comment]
Mid point snapping can be easily achieved by subdividing the segment (hotkey W in Flexi Edit) with single node in the middle. The new Bezier point is subsequently available for snapping with alt.
Also please use the BlenderArtists thread: https://blenderartists.org/t/flexi-bezier-tool/1168179 for feature requests. This allows brainstorming the ideas with the existing users.
It's better to reserve this Github issues page for Issues (i.e. defects) only.
