### ISSUE TITLE
Buglet: The "display next to toolbar" option does not work as expected

### ISSUE THREAD

**Issue by raindropsfromsky** [Shriinivas/blenderbezierutils#23]
The keymap appears in the left-side bottom corner of the screen. There is an option to shift this display next to the toolbar, but when I have folded the toolbar in two-column configuration, the text appears far from the toolbar.

![image](https://user-images.githubusercontent.com/9047168/89897522-c6192680-dbfc-11ea-9b89-0aa65e8ced85.png)

In my case, I have changed the font size to 15, but even when I reset the preferences, the result is similar.

**Comment by Shriinivas** [comment]
Next to toolbar actually means horizontally adjacent to toolbar. This option is provided to prevent overlapping of the display map with the toolbar in case the viewport is too small. There is an option in the preferences to manually adjust the position of the display map in case you want a finer control on its location.
