### ISSUE TITLE
Feature request: Allow user to fold a 3D bezier curve 

### ISSUE THREAD

**Issue by raindropsfromsky** [Shriinivas/blenderbezierutils#24]
Imagine that we have drawn a shape on a paper, and then we fold the paper in the middle. The original shape is not changed, but now both parts of the shape lie at an angle.

Can we have this type of effect in the Bezier Curve addon?

Note that the curve can cross the fold at one place or multiple places. (or, multiple curves may go across the fold.)
In all cases, the folding angle should be the same for all curves that cross the fold.

**Comment by Shriinivas** [comment]
This looks like a snap to Mesh surface featrure, which again is under review. Please use the BlenderArtists thread: https://blenderartists.org/t/flexi-bezier-tool/1168179 for feature requests. This allows brainstorming the ideas with the existing users.
It's better to reserve this Github issues page for Issues (i.e. defects) only.
