### ISSUE TITLE
Unable to use the DEL button to delete anything in the bezier curve

### ISSUE THREAD

**Issue by raindropsfromsky** [Shriinivas/blenderbezierutils#25]
I have 101 keys ("full") keyboard on my Acer Aspire laptop, with a NumPad at right.
The keyboard has the standard "US" layout (English).

I am using Blender 2.91 (downloaded 2 days ago), on Windows 10 Home edition, 64 bits.

If I use the DEL button located in the NumPad, nothing happens. 
- I tried toggling the NumLock button. No change.
- I tried selecting different options (everything, curve object, segments, bezier points...). No change. 

But the button on the top row of the keyboard, which is labeled **Ins/DEL** works fine.
Both buttons are shown in this figure:
![image](https://user-images.githubusercontent.com/9047168/89937795-304cbe00-dc33-11ea-9dee-be80fcb8baa4.png)

The sample bezier curve is shown below (just to check if I am using the correct mode, selection, etc)
![image](https://user-images.githubusercontent.com/9047168/89930279-207bac80-dc28-11ea-9c07-2e7d8be4c4c7.png)

**Comment by Shriinivas** [comment]
Within Blender Del and Numpad Del are two different keys. If you want to invoke the delete operation in Flexi Edit via Numpad Del, please assign the key in the keymap. The add-on currently supports assignment of only one key combination per operation.
