### ISSUE TITLE
Feature request: Box-select parts of curve(s)

### ISSUE THREAD

**Issue by raindropsfromsky** [Shriinivas/blenderbezierutils#26]
Currently, we have to select segments of a curve one by one. 
It would be fantastic if the user can use the **box-select tool** to (de)select multiple segments at a time.

**Comment by Shriinivas** [comment]
Thank you for your inputs. Please use the BlenderArtists thread: https://blenderartists.org/t/flexi-bezier-tool/1168179 for feature requests. This allows brainstorming the ideas with the existing users.
It's better to reserve this Github issues page for Issues (i.e. defects) only.
