### ISSUE TITLE
Feature request: When we want to draw a curve from a node of another curve, highlight the node

### ISSUE THREAD

**Issue by raindropsfromsky** [Shriinivas/blenderbezierutils#27]
Suppose we want to draw a Bezier curve from another existing curve, either from an end-point or another node in the middle.
When I select the **Draw Bezier** tool and hover the pointer on the curve, none of the nodes on the old curve are highlighted, 

**Desired:** We should be able to snap the starting point to any of the nodes of the older curve, and that should be visually indicated.

**Comment by Shriinivas** [comment]
You can enable the snap point indicator via add-on preferences:
![Snap Indicator](https://user-images.githubusercontent.com/42069100/90138495-b7fe0e00-dd94-11ea-9259-68f2073c79f2.png)
