### ISSUE TITLE
In Blender2.90, when I run "Mark Starting Vertices", it crashes.

### ISSUE THREAD

**Issue by bookyakuno** [Shriinivas/blenderbezierutils#28]
In Blender2.90, when I run "Mark Starting Vertices", it crashes.
This is probably a problem caused by the specification change in 2.90, which changed the option name of the curve handle display.

old …… show_curve_handles
new …… display_handle

## System info

version: 2.90.0, branch: master, commit date: 2020-08-31 11:26, hash: 0330d1af29c0, type: Release
build date: 2020-08-31, 10:00:13
platform: Windows
binary path: 'C:\\Program Files\\blender-2.90\\blender290.exe'
build cflags: /W3 /w34062 /w34115 /w34189 /wd4018 /wd4146 /wd4065 /wd4127 /wd4181 /wd4200 /wd4244 /wd4267 /wd4305 /wd4800 /wd4828 /wd4996 /wd4661 /we4013 /we4133 /we4431 /w35038 /DWIN32 /D_WINDOWS /W3 /nologo /J /Gd /MP /bigobj -openmp     
build cxxflags: /W3 /w34062 /w34115 /w34189 /wd4018 /wd4146 /wd4065 /wd4127 /wd4181 /wd4200 /wd4244 /wd4267 /wd4305 /wd4800 /wd4828 /wd4996 /wd4661 /we4013 /we4133 /we4431 /w35038 /DWIN32 /D_WINDOWS /W3 /GR /EHsc /nologo /J /Gd /MP /EHsc /bigobj /permissive- /Zc:twoPhase- -openmp /std:c++17     
build linkflags: /MACHINE:X64  /SUBSYSTEM:CONSOLE /STACK:2097152 /ignore:4049 /ignore:4217 /ignore:4221
build system: CMake

**Comment by Shriinivas** [comment]
Thanks, yes the issue was because of the change in API in 2.90.
Have fixed the issue in the latest version. Kindly confirm.

**Comment by bookyakuno** [comment]
I confirmed. Good job👍
