### ISSUE TITLE
2.90.1 Adjusting number of segments Freeze Error

### ISSUE THREAD

**Issue by summereasy** [Shriinivas/blenderbezierutils#30]
It's such a Great Addon you are marvelous! 
I got an error when I try to segment circles and polygons.

**Blender Version: 2.90.1 (Mac OS)**
**Addon Version: 0.9.95**

When I try to scroll my mouse and/or use the Numpad +/- to change the segment blender showed me an error message and the addon appears to be freeze and I couldn't do anything after that.

![image](https://user-images.githubusercontent.com/51897649/95416453-66719a00-0965-11eb-9c25-e27f7de65cf7.png)

I don't know if I'm doing it wrong or it is just caused by some other issue.
Look forward to see some new cool ideas from it!

**Comment by Shriinivas** [comment]
Thank you for reporting this. I just missed to test this functionality after the new changes.
The bug is fixed in the latest upload. Kindly check and confirm.

**Comment by summereasy** [comment]
Again, great work! Thanks and closing ~
