### ISSUE TITLE
alpha transparency problem

### ISSUE THREAD

**Issue by AMYO77** [Shriinivas/blenderbezierutils#36]
Hi sorry to bother you , i use your addon a lot and there is a problem with guizmo alpha transparency in blender 2.91.
Is it possible to fix it ?
Thanks for your work, this is a great addon.

(I know it's coming from this addon because as soon as i disabled it, no more problem)

![Sans titre](https://user-images.githubusercontent.com/22004001/100550790-a45fb000-327c-11eb-9f80-d90039acbbc7.png)

**Comment by Shriinivas** [comment]
The issue is fixed now.
