### ISSUE TITLE
The addon crashes Blender when exporting anything to alembic

### ISSUE THREAD

**Issue by riouxr** [Shriinivas/blenderbezierutils#38]
I figured it out by looking at the crash file. In it, this line:

  File "/home/rrioux/.config/blender/2.90/scripts/addons/blenderbezierutils.py", line 2670 in colorCurves

So I turned off the addon and it worked.

**Comment by Shriinivas** [comment]
Did you try with the latest version of the add-on. 
There has been a fix in colorCurves just a couple of days back.

**Comment by Shriinivas** [comment]
Please reopen the issue if the problem persists with the latest version (0.9.96).
