### ISSUE TITLE
Blender 2.92a segmentation fault when the bezierutils addon is enabled

### ISSUE THREAD

**Issue by meikasahara** [Shriinivas/blenderbezierutils#39]
In the latest Blender 2.92 Alpha build, with the latest (0.99.5) bezierutils addon enabled, when marking any object other than a collection as an asset using the new asset manager, blender crashes with a segmentation fault:

`Info: Data-block 'Cube' is now an asset

Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f1250a3f210]
#1  /lib/x86_64-linux-gnu/libGLdispatch.so.0(+0x4c049) [0x7f1250933049]
`
This behavior occurs only when the bezierutils addon is enabled, whereas when it is disabled, the asset operation proceeds normally without crashes.

**Comment by Shriinivas** [comment]
Please check with the latest version (0.9.96). Let me know if you still face issues.

**Comment by meikasahara** [comment]
The problem has been fixed and now it works as expected, thank you!
