### ISSUE TITLE
small help font when using 4k monitor 

### ISSUE THREAD

**Issue by figihiuy** [Shriinivas/blenderbezierutils#40]
small  font of help when using 4k monitor .please fix.

![image](https://user-images.githubusercontent.com/69837796/106742082-df58d800-665f-11eb-9f85-b5810c12f358.png)

**Comment by summereasy** [comment]
**I think you should check your options first before asking for a "fix":**
I got 5K monitors, and by setting the correct font size, the addon should work flawlessly.


`Preference Menu for Addon`
![iShot2021-02-03 21 48 21](https://user-images.githubusercontent.com/51897649/106756409-3cf22200-666a-11eb-9808-204b595fddd3.jpg)

`And the screen`
![iShot2021-02-03 21 50 27](https://user-images.githubusercontent.com/51897649/106756639-6ad76680-666a-11eb-810c-00bbb02204cf.jpg)

**Comment by figihiuy** [comment]
Thank you very much!
