### ISSUE TITLE
Flexi Bezier Tools not showing up on addon list

### ISSUE THREAD

**Issue by mvxxgh** [Shriinivas/blenderbezierutils#42]
After installing the Add-on, I'm not seeing the it in the Add-on list to enable it.  I'm on Blender 2.91.0
![2021-03-13 15_38_20-](https://user-images.githubusercontent.com/80605161/111052748-a2c48d00-8412-11eb-9671-93097b39dd56.png)
![2021-03-13 15_39_11-Window](https://user-images.githubusercontent.com/80605161/111052766-d0a9d180-8412-11eb-9e15-b89cbf1e8669.png)

**Comment by ChristinaMcKay** [comment]
That happens when you use the zip for the installation. Grab the .py file and install only that Python file, that should work fine.
Cheers, Christina

**Comment by mvxxgh** [comment]
Thank you for replying to this issue.  I installed using the blenderbezierutils.py not a .zip.

**Comment by ChristinaMcKay** [comment]
Hi. did you right click the file name in the file list? If so, you might not have the python file but the html.
Did you open the .py with an editor to check?
If you scroll a bit down on the page with the files, under the headline Installation he writes:
Download blenderbezierutils.py (save the file from this location in a folder on disk.)
"this location" is a link. Right click that and save the file.
I never had issues although there might be one with your system and Shriinivas then has to look into that.
But please first check the file you downloaded, if that really is the code.
You can also left click the .py in the file list, then you see the code. You can copy the code, put it into any editor like notepad, Atom etc and save it as .py.
Cheers

**Comment by mvxxgh** [comment]
Yes I can confirm I installed the blenderbezierutils.py.  Blender reports at the bottom of the screen "module installed" I've screenshotted above.  After that report, I go to enable the add-on through the list but searching for it doesn't pull anything up.

**Comment by ChristinaMcKay** [comment]
That Blender message means nothing, to be honest. You also get that when you try to install the zip.
so it works now?
Which Blender Version are you using?

**Comment by mvxxgh** [comment]
I'm not sure what I did different but I redownloaded and installed again and now it works just fine.

**Comment by Shriinivas** [comment]
Thank you very much @ChristinaMcKay for your kind help.
I am closing the issue since user no more has any problems.
