### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by rajq123** [Shriinivas/blenderbezierutils#43]
It is about increasing functionality not a Issue report: Please enable same feature like in grease pencil scroll wheel to adjust subdivision/resolution of the curve in 3d viewport, however i think you don't include maybe due to stability issue but please have an option to enable it. In archviz it is very helpful. In 3ds max, 80 percent of architectural modelling work is done is Spline why blender don't emphasize on improving curve functionality even in after effect animation curve is used heavily, simple operation like auto-smooth are not yet present. Boolean modifier will be great. Anyway if you find time then only work on it.

**Comment by Shriinivas** [comment]
Please use this blenderartists thread for feature requests: https://blenderartists.org/t/flexi-bezier-tool/1168179
It will allow other users to comment and contribute.
