### ISSUE TITLE
BGL to be discontinued in 3.7

### ISSUE THREAD

**Issue by CurtisDitto** [Shriinivas/blenderbezierutils#54]
Using bezierutils in 3.5 beta, and this error is coming up:
<img width="565" alt="image" src="https://user-images.githubusercontent.com/48217676/221652411-6c06ba61-ac5f-475d-94ad-e802e891ca14.png">

And this:
WARN (bgl): source/blender/python/generic/bgl.c:2656 BPyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module. In Blender 3.7 'bgl' will be removed.

Everything still works if I use OpenGL instead of Metal.

Looked at the code a bit, and looks like bgl is only used for determining line width and point size, such as with bgl.glPointSize(MarkerController.defPointSize. Also read up that this may be the only way to change pointsize and line width, although I have to admit that the ability to change line width and point size as a custom preference never worked for me in the first place. I tried commenting out the bgl lines and no longer receive any errors, and everything seems to work as well as it did before.

**Comment by Shriinivas** [comment]
This is fixed, please check with Blender ver 4.
