### ISSUE TITLE
OpenGL issue in 3.6 to ...

### ISSUE THREAD

**Issue by nurb2kea** [Shriinivas/blenderbezierutils#58]
![Screenshot 2023-07-18 at 5 46 56 pm](https://github.com/Shriinivas/blenderbezierutils/assets/57676085/d3cb00d5-bc59-4e2a-8613-e739e6f5835a)

**Comment by nurb2kea** [comment]
?

**Comment by Shriinivas** [comment]
This is fixed in the tool now. Please check with Blender ver 4 and let me know if you still have problems.
