### ISSUE TITLE
We need to preserve this tool for Blender 4.0 and beyond

### ISSUE THREAD

**Issue by abhiraaid** [Shriinivas/blenderbezierutils#59]
Right now, Flexi Bezier Tool doesn't get installed in Blender 4.0. 

![image](https://github.com/Shriinivas/blenderbezierutils/assets/108699606/04d0c226-90eb-4a0b-b377-febbaeb60054)

**Comment by ChristinaMcKay** [comment]
1+

**Comment by cx1132692358** [comment]
1+

**Comment by Shriinivas** [comment]
The issues are fixed now, please test the tool in version 4 and let me know if you still face any issues.

**Comment by abhiraaid** [comment]
> The issues are fixed now, please test the tool in version 4 and let me know if you still face any issues.

Thankyou so much man. It's working :smile:
