### ISSUE TITLE
Blender crashes on multi-window setup opening one-window startup file

### ISSUE THREAD

**Issue by crantisz** [Shriinivas/blenderbezierutils#6]
**System Information**
Operating system: Linux-4.15.0-62-generic-x86_64-with-debian-buster-sid 64 Bits
Graphics card: GeForce GTX 1070/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 390.116

**Blender Version**
Broken: version: 2.81 (sub 15), branch: master, commit date: 2019-10-12 15:33, hash: `rB95f020c853d6`

**Bezier utils version**
0.9.61 version used.

**Exact steps for others to reproduce the error**
* Enable Bezier utils addon
* Window -> New window.
* Save Startup File (maybe doesn't matter)
* File -> New -> select any workspace with one window
* Crash

[blender.crash.txt](https://github.com/Shriinivas/blenderbezierutils/files/3724142/blender.crash.txt)

**Comment by Shriinivas** [comment]
Fixed in the latest version. Please check and confirm.

**Comment by crantisz** [comment]
Look like it was fixed
