### ISSUE TITLE
Not installing on any blender versions

### ISSUE THREAD

**Issue by kebab03** [Shriinivas/blenderbezierutils#62]
I tried  to install on blender 2.90- 2.91 - 3.0 - 3.3 . 3.5  in each version I get   mod = __import__(module_name)
ModuleNotFoundError: No module named 'blenderbezierutils_2'           for       blenderbezierutils28.py file   While I get                                                                       File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\Sharif\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blenderbezierutils.py", line 10835, in register
    BezierUtilsPanel.colorCurves(add = True)
  File "C:\Users\Sharif\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blenderbezierutils.py", line 2798, in colorCurves
    BezierUtilsPanel.shader = gpu.shader.from_builtin('FLAT_COLOR')
ValueError: unknown type literal: 'FLAT_COLOR'                                                 for  blenderbezierutils.py.

**Comment by kushag09** [comment]
If you are trying on 3.5, I suggest you install the blenderbezierutils.py, not the 2.8 one. About the FLAT_COLOR issue, open the addon file, and find and replace all the "FLAT_COLOR" to "3D_FLAT_COLOR".
