### ISSUE TITLE
Tool doesn't work entire surface of the screen

### ISSUE THREAD

**Issue by rajinder-yadav** [Shriinivas/blenderbezierutils#8]
Please see following video for bug: https://www.youtube.com/watch?v=_Iw85AgSVPs

I am using Linux openSuse Tumbleweed, and my screen resolution is 1920x1200

Blender 2.80

**Comment by Shriinivas** [comment]
This is a Known Issue (please refer to the Known Issue section in the documentation), caused by limitations of the python API. As mentioned in the documentation, to make the entire screen area available for drawing, just hide the properties panel (hotkey: n) and the toolshelf (hotkey: t).
